### ISSUE TITLE
adverts/user-messaging-platform

### ISSUE THREAD

**Issue by yrozijn** [airnativeextensions/nativeextensions-documentation#2]
File: adverts/user-messaging-platform
In section "Present the form if required", it doesn't describe how I know that the user has closed the form and I can continue initializing the ad platform.
I presume that it dispatches a `UserMessagingPlatformEvent.CONSENT_FORM_DISMISSED` event?

**Comment by marchbold** [comment]
Yes that is correct.

The `showConsentForm()` process will dispatch the `ConsentInformationEvent.CONSENT_FORM_DISMISSED` event when the consent form was dismissed.

```actionscript
Adverts.service.ump.addEventListener( UserMessagingPlatformEvent.CONSENT_FORM_DISMISSED, formDismissedHandler );
Adverts.service.ump.showConsentForm();

function formDismissedHandler( event:UserMessagingPlatformEvent ):void 
{
    // Handle form dismissal
}
```
